[env]
platform = espressif32@6.2.0
framework = arduino

board_build.flash_mode = qio
board_build.f_flash = 80000000L

lib_deps = m5stack/M5Unified
    https://github.com/arslan437/EspFileManager.git
    ESP32Async/AsyncTCP
    ESPAsyncWebServer
    ArduinoJson
    DNSServer

lib_ldf_mode = deep
lib_compat_mode=strict
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
board_build.partitions = no_ota.csv

build_flags = -Wextra -Wreturn-local-addr -Werror=format -Werror=return-local-addr
  -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue

; --------------------------------
; Choose build options
[option_release]
build_flags =  -DCORE_DEBUG_LEVEL=3
 -DLOG_LOCAL_LEVEL=3
 -DAPP_LOG_LEVEL=3

[option_log]
build_flags =  -DCORE_DEBUG_LEVEL=5
 -DLOG_LOCAL_LEVEL=5
 -DAPP_LOG_LEVEL=5

[option_debug]
build_flags =  -DCORE_DEBUG_LEVEL=5
 -DLOG_LOCAL_LEVEL=5
 -DAPP_LOG_LEVEL=5
 -DDEBUG

;----
[env:release]
board = esp32s3box
board_build.arduino.memory_type = qio_qspi
upload_speed = 1500000
build_type=release
build_flags=${env.build_flags} ${option_release.build_flags}
